import type { Metadata } from "next";
import { Bodoni_Moda, Cormorant_Garamond } from "next/font/google";
import "@/app/globals.css";
import ReelViewerProvider from "@/components/reels/ReelViewerProvider";
import { GtmScript, GtmNoScript, GtmConsentDefault } from "@/components/Analytics";
import ConsentBanner from "@/components/ConsentBanner";
import { Analytics } from "@vercel/analytics/next";
import { Suspense } from "react";
import AttributionCapture from "@/components/AttributionCapture";
import FloatingReserva from "@/components/FloatingReserva";
import Clarity from "@/components/Clarity";
import { SITE_URL, alternatesForEn } from "@/lib/i18n";
import { reviewStats, reviewStatsEn } from "@/data/reviews";

const bodoni = Bodoni_Moda({
  subsets: ["latin"],
  variable: "--font-bodoni",
  weight: ["400", "500", "600"],
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorant",
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Positano · Neapolitan Pizza & Italian Restaurant in the Eixample",
  description:
    `Neapolitan pizzeria and Italian restaurant in the Eixample, Barcelona: fresh pasta, carbonara and wood-fired pizza. ${reviewStatsEn.rating}★ from ${reviewStatsEn.count} reviews.`,
  keywords: [
    "italian restaurant barcelona",
    "neapolitan pizza barcelona",
    "best pizza barcelona",
    "pizza barcelona",
    "italian restaurant eixample",
    "pizza delivery barcelona",
  ],
  alternates: alternatesForEn("/en"),
  openGraph: {
    type: "website",
    locale: "en_GB",
    alternateLocale: "es_ES",
    siteName: "Positano Pizzería",
    title: "Positano · Neapolitan Pizza & Italian Restaurant Barcelona",
    description:
      "Neapolitan pizzeria and Italian restaurant in the Eixample, Barcelona: fresh pasta, carbonara and wood-fired pizza. One of the neighbourhood's best-rated Italians.",
    url: `${SITE_URL}/en`,
    // The shareable image is generated by src/app/(en)/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: "Positano · Neapolitan Pizza & Italian Restaurant Barcelona",
    description:
      "Neapolitan pizza, fresh pasta and the carbonara locals recommend. One of the best-rated Italians in the Eixample, Barcelona.",
  },
};

// Structured data — helps Google understand the local business (English).
const restaurantJsonLd = {
  "@context": "https://schema.org",
  "@type": "Restaurant",
  name: "Positano Pizzería",
  description:
    "Neapolitan pizzeria and Italian restaurant in the Eixample, Barcelona. Wood-fired pizza, fresh pasta (its carbonara is among the most recommended) and pistachio tiramisù; one of the best-rated Italians in the neighbourhood, known for its warm service.",
  url: `${SITE_URL}/en`,
  telephone: "+34933515913",
  email: "positanopizzeria2023@gmail.com",
  image: `${SITE_URL}/hero/positano.jpg`,
  priceRange: "€€",
  servesCuisine: ["Neapolitan pizza", "Fresh pasta", "Italian", "Pasta"],
  acceptsReservations: true,
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: reviewStats.rating.replace(",", "."),
    reviewCount: reviewStats.count.replace(/\D/g, ""),
  },
  address: {
    "@type": "PostalAddress",
    streetAddress: "Carrer del Rosselló, 24",
    addressLocality: "Barcelona",
    addressRegion: "Barcelona",
    postalCode: "08029",
    addressCountry: "ES",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: 41.3845148,
    longitude: 2.1458994,
  },
  hasMap:
    "https://www.google.com/maps/search/?api=1&query=Positano+Pizzeria&query_place_id=ChIJsRxSfvqjpBIR1V-jzgurn2U",
  areaServed: "Barcelona",
  sameAs: [
    "https://www.instagram.com/positanopizzeriabcn/",
    "https://www.facebook.com/positanopizzeriabcn/",
    "https://www.thefork.es/restaurante/positano-r804685",
    "https://www.tripadvisor.es/Restaurant_Review-g187497-d25455989-Reviews-POSITANO_PIZZERIA-Barcelona_Catalonia.html",
    "https://www.google.com/maps?cid=7322759586327519189",
    "https://glovoapp.com/en/es/barcelona/stores/positano-pizzeria-barcelona",
    "https://www.ubereats.com/es/store/positano-pizzeria/ciPAhMptSOeZGNeUsyhjKA",
  ],
  hasMenu: `${SITE_URL}/en/menu`,
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Tuesday", "Wednesday", "Thursday"],
      opens: "13:00",
      closes: "16:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Tuesday", "Wednesday", "Thursday"],
      opens: "20:00",
      closes: "23:30",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Friday",
      opens: "13:00",
      closes: "16:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Friday",
      opens: "20:00",
      closes: "00:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Saturday",
      opens: "13:00",
      closes: "00:00",
    },
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: "Sunday",
      opens: "13:00",
      closes: "23:30",
    },
  ],
};

export default function EnLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bodoni.variable} ${cormorant.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        {/* GTM/gtag weigh ~330 KB: preconnecting saves ~350 ms on mobile
            (Lighthouse). React hoists this into the <head>. */}
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <GtmConsentDefault />
        <GtmNoScript />
        <noscript>
          <style>{`.hero-rise,[data-reveal]{opacity:1!important;transform:none!important;animation:none!important;}`}</style>
        </noscript>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(restaurantJsonLd) }}
        />
        <ReelViewerProvider lang="en">{children}</ReelViewerProvider>
        <FloatingReserva lang="en" />
        <ConsentBanner lang="en" />
        <GtmScript />
        <Clarity />
        <Analytics />
        <Suspense>
          <AttributionCapture />
        </Suspense>
      </body>
    </html>
  );
}
